add -o output path option + set git config core.fileMode true

diff --git a/stemgen b/stemgen
--- a/stemgen
+++ b/stemgen
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+# Exit on use of an uninitialized variable
+# set -o nounset
+# Exit if any statement returns a non-true return value (non-zero).
+# set -o errexit
+
 LOGO="
  _____ _____ _____ _____ _____ _____ _____ 
 |   __|_   _|   __|     |   __|   __|   | |
@@ -13,21 +18,26 @@ SUPPORTED_FILES=('.wav' '.wave' '.aif' '.aiff' '.flac')
 USAGE="$LOGO
 Stemgen is a Stem file generator. Convert any track into a stem and have fun with Traktor.
 
-Usage: $0 -i [path]
+Usage: $0 -i [input_path] -o [output_path]
 
 Supported input file format: ${SUPPORTED_FILES[@]}
 "
-VERSION=1.0.0
+VERSION=1.0.1
 
 INPUT_PATH=
+OUTPUT_PATH=output
 BASE_PATH=
 FILE_NAME=
 FILE_EXTENSION=
 
+# From https://stackoverflow.com/a/53183593
+DIR="$(dirname "${BASH_SOURCE[0]}")" # get the directory name
+DIR="$(realpath "${DIR}")" # resolve its full path if need be
+
 get_cover() {
     echo "Extracting cover..."
 
-    ffmpeg -i "$INPUT_PATH" -an -vcodec copy "output/$FILE_NAME/cover.jpg" -y
+    ffmpeg -i "$INPUT_PATH" -an -vcodec copy "$OUTPUT_PATH/$FILE_NAME/cover.jpg" -y
 
     echo "Done."
 }
@@ -35,7 +45,7 @@ get_cover() {
 get_metadata() {
     echo "Extracting metadata..."
 
-    ffmpeg -i "$INPUT_PATH" -f ffmetadata "output/$FILE_NAME/metadata.txt" -y
+    ffmpeg -i "$INPUT_PATH" -f ffmetadata "$OUTPUT_PATH/$FILE_NAME/metadata.txt" -y
 
     echo "Done."
 }
@@ -43,7 +53,7 @@ get_metadata() {
 convert_to_wav() {
     echo "Converting to wav..."
 
-    ffmpeg -i "$INPUT_PATH" -map_metadata 0:s:0 "output/$FILE_NAME/$FILE_NAME.wav" -y
+    ffmpeg -i "$INPUT_PATH" -map_metadata 0:s:0 "$OUTPUT_PATH/$FILE_NAME/$FILE_NAME.wav" -y
 
     echo "Done."
 }
@@ -51,7 +61,7 @@ convert_to_wav() {
 create_tags_json() {
     echo "Creating tags.json..."
 
-    cd "output/$FILE_NAME"
+    cd "$OUTPUT_PATH/$FILE_NAME"
 
     local path=$( cd "$(dirname "$FILE_NAME")" >/dev/null 2>&1 ; pwd -P )
 
@@ -69,7 +79,8 @@ create_tags_json() {
             tags+=("track=${value}")
         elif [[ $title == "artist" ]] || [[ $title == "label" ]] ||
            [[ $title == "genre" ]] || [[ $title == "release" ]] ||
-           [[ $title == "comment" ]] || [[ $title == "comment2" ]]; then
+           [[ $title == "comment" ]] || [[ $title == "comment2" ]] ||
+           [[ $title == "bpm" ]] || [[ $title == "initialkey" ]]; then
             tags+=("${title}=${value}")
         fi
     done < metadata.txt
@@ -91,7 +102,7 @@ create_tags_json() {
 split_song() {
     echo "Splitting song..."
 
-    spleeter separate -i "$INPUT_PATH" -p spleeter:4stems-16kHz -o output
+    spleeter separate -i "$INPUT_PATH" -p spleeter:4stems-16kHz -o "$OUTPUT_PATH"
 
     echo "Done."
 }
@@ -99,7 +110,8 @@ split_song() {
 create_stem() {
     echo "Creating stem..."
 
-    ./ni-stem/ni-stem create -s "output/$FILE_NAME/drums.wav" "output/$FILE_NAME/bass.wav" "output/$FILE_NAME/other.wav" "output/$FILE_NAME/vocals.wav" -x "output/$FILE_NAME/$FILE_NAME.wav" -t "output/$FILE_NAME/tags.json" -m metadata.json -f alac
+    cd "$DIR"
+    ./ni-stem/ni-stem create -s "$OUTPUT_PATH/$FILE_NAME/drums.wav" "$OUTPUT_PATH/$FILE_NAME/bass.wav" "$OUTPUT_PATH/$FILE_NAME/other.wav" "$OUTPUT_PATH/$FILE_NAME/vocals.wav" -x "$OUTPUT_PATH/$FILE_NAME/$FILE_NAME.wav" -t "$OUTPUT_PATH/$FILE_NAME/tags.json" -m metadata.json -f alac
 
     echo "Done."
 }
@@ -107,7 +119,7 @@ create_stem() {
 clean_dir() {
     echo "Cleaning..."
 
-    cd "output/$FILE_NAME"
+    cd "$OUTPUT_PATH/$FILE_NAME"
     if [[ -f "$FILE_NAME.stem.m4a" ]]; then
         mv "$FILE_NAME.stem.m4a" ..
     else
@@ -124,10 +136,10 @@ setup_file() {
     FILE_EXTENSION=$1
     FILE_NAME=${BASE_PATH%"$FILE_EXTENSION"}
 
-    if [[ -d "output/$FILE_NAME" ]]; then
+    if [[ -d "$OUTPUT_PATH/$FILE_NAME" ]]; then
         echo "Working dir already created."
     else
-        mkdir "output/$FILE_NAME"
+        mkdir "$OUTPUT_PATH/$FILE_NAME"
         echo "Working dir created."
     fi
 }
@@ -146,10 +158,10 @@ setup() {
         exit 2
     fi
 
-    if [[ -d output ]]; then
+    if [[ -d $OUTPUT_PATH ]]; then
         echo "Output dir already created."
     else
-        mkdir output
+        mkdir $OUTPUT_PATH
         echo "Output dir created."
     fi
 
@@ -158,11 +170,11 @@ setup() {
     case "$INPUT_PATH" in
         *.wave)
             setup_file .wave
-            cp "$INPUT_PATH" "output/$FILE_NAME/$FILE_NAME.wav"
+            cp "$INPUT_PATH" "$OUTPUT_PATH/$FILE_NAME/$FILE_NAME.wav"
             ;;
         *.wav)
             setup_file .wav
-            cp "$INPUT_PATH" "output/$FILE_NAME/$FILE_NAME.wav"
+            cp "$INPUT_PATH" "$OUTPUT_PATH/$FILE_NAME/$FILE_NAME.wav"
             ;;
         *.aiff)
             setup_file .aiff
@@ -174,6 +186,14 @@ setup() {
             ;;
         *.flac)
             setup_file .flac
+            convert_to_wav
+            ;;
+        *.stem.mp4)
+            setup_file .stem.mp4
+            convert_to_wav
+            ;;
+        *.stem.m4a)
+            setup_file .stem.m4a
             convert_to_wav
             ;;
         *)
@@ -202,6 +222,9 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
     -V | --version)
         echo $VERSION
         exit 0
+        ;;
+    -o | --output)
+        shift; OUTPUT_PATH=$1
         ;;
     -i | --input)
         shift; INPUT_PATH=$1
